server:
  port: ${PORT:8080}


spring:
  application:
    name: customer-service
  profiles:
    active: dev
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:customerdb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    
logging:
  level:
    com: DEBUG
  pattern:
    console: '%d{yyyy-MM-dd HH:mm:ss} - %msg%n'



springdoc:
  api-docs:
    path: /v3/api-doc
  swagger-ui:
    path: /swagger-ui
    
